### ISSUE TITLE
webpack.config.js自定义的loader 最终会用2次

### ISSUE THREAD

**Issue by feix760** [easy-team/easywebpack#41]
https://github.com/easy-team/easywebpack/blob/54f3cf8b7ed98e86c806a588c01f5353eda36c26/lib/builder.js#L37

这个地方的merge最终会导致webpack.config.js定义的Loader加两次

例如webpack.config.js配置：

```javascript
  // webpack.config.js
  loaders: {
    html: {
      test: /\.html$/,
      use: [
        {
          loader: 'html-loader',
          options: {
            interpolate: 'require', // supported html `${}` sytax
            attrs: [ ':src' ],
          },
        },
      ],
    },
 }
```

最终的结果：

<img width="468" alt="2018-10-15 3 30 34" src="https://user-images.githubusercontent.com/5415656/46936149-fab70800-d08f-11e8-9345-606e97db67b0.png">

**Comment by hubcarl** [comment]
@feix760  easywebpack最近进行了重构， easywebpack-cli 发布 v4 版本，导致easywebpack-cli v3 配置合并重复， 已发布 easywebpack-cli@3.12.1 解决 https://github.com/easy-team/easywebpack-cli/commit/20bcff2
