### ISSUE TITLE
生产环境打包，script引入js的路径没有替换成绝对路径

### ISSUE THREAD

**Issue by countingSta** [easy-team/easywebpack#42]
'use strict';
const path = require('path');
const VueLoaderPlugin = require('vue-loader/lib/plugin');
const optimizeCssAssets = require('optimize-css-assets-webpack-plugin');
const Oss = require('./plugins/oss');

module.exports = {
    egg: true,
    framework: 'vue',
    entry: {
        include: ['app/web/page'],
        exclude: ['app/web/page/[a-z]+/(component|store)'],
        loader: {
            client: 'app/web/framework/vue/entry/client-loader.ts',
            server: 'app/web/framework/vue/entry/server-loader.ts'
        }
    },
    // publicPath: process.env.NODE_ENV === 'production' ? 'https://cdn.dooprime.com/clearing-website/dist/' : '/public/',
    alias: {
        server: 'app/web/framework/vue/entry/server.ts',
        client: 'app/web/framework/vue/entry/client.ts',
        component: 'app/web/component',
        framework: 'app/web/framework',
    },
    dll: ['vue'],
    loaders: {
        typescript: true,
        less: true,
        stylus: true
    },
    plugins: {
        vueLoader: {
            name: new VueLoaderPlugin()
        },
        optimizeCssAssets: {
            name: new optimizeCssAssets(),
            env: ['prod']
        }
    }
};
![image](https://user-images.githubusercontent.com/24948358/48006895-63eee000-e151-11e8-8704-d4de841c775c.png)

**Comment by hubcarl** [comment]
@countingSta  不要在publicPath 上面配置cdn这个，另外  process.env.NODE_ENV === 'production' 判断， process.env.NODE_ENV  这个值 你是否有设置？  CDN 配置： https://www.yuque.com/easy-team/easywebpack/cdn

**Comment by hubcarl** [comment]
optimize-css-assets-webpack-plugin 已内置，并开启了，无需配置

**Comment by hubcarl** [comment]
const VueLoaderPlugin = require('vue-loader/lib/plugin');  引入这个是做什么？

**Comment by hubcarl** [comment]
目前 easywebpack 内置方案是 vue-loader 版本是 14，无需相关插件配置。 15 还需要等一段时间

**Comment by hubcarl** [comment]
已内置 15
