### ISSUE TITLE
Node 10.13下打包会报错

### ISSUE THREAD

**Issue by lcsoftware** [easy-team/easywebpack#43]
node_modules/easywebpack-vue/node_modules/easywebpack/index.js:13

exports.getConfig = config => require('./lib/config')(config);
                                                     ^
TypeError: Class constructor Config cannot be invoked without 'new'

**Comment by hubcarl** [comment]
@lcsoftware  请检查一下easywebpack-vue 和 easywebpack-cli  的版本不匹配  包括 全局按照 的 easywebpack-cli
