### ISSUE TITLE
发现process is not defined

### ISSUE THREAD

**Issue by renzhengxiao** [easy-team/easywebpack#45]
在4.10.0版本中发现process is not defined,使用process的是_process-nextick-args@2.0.0@process-nextick-args 这个插件，使用这个插件的是cheerio插件

**Comment by hubcarl** [comment]
@renzhengxiao   webpack.config.js 配置加上 node : { process: true } , 新版本我默认是false，我现在开启一下

**Comment by hubcarl** [comment]
新版本已默认开启
