### ISSUE TITLE
exports.vuessr????where is exports.reactssr

### ISSUE THREAD

**Issue by lyj505** [easy-team/easywebpack#48]
是不是不支持reactssr的配置项啊,,,我在项目通过注释的写法
/* webpackChunkName: "show" */ 去异步引入组件 渲染是可以渲染 但是还是渲染到目录为enrty ssr.js里面了,并没有chunk?????生成 我webpack.config.js 也配置了也不行。。。。

**Comment by hubcarl** [comment]
- https://www.yuque.com/easy-team/egg-vue
- https://www.yuque.com/easy-team/egg-react
