### ISSUE TITLE
有egg项目模板渲染的前端资源工程化方案骨架吗？或者基于easywebpack配置的例子，请教解决思路！

### ISSUE THREAD

**Issue by gongdf** [easy-team/easywebpack#49]

**Comment by hubcarl** [comment]
@gongdf see  https://www.yuque.com/easy-team/egg-vue/web  和 https://www.yuque.com/easy-team/egg-react/web

**Comment by gongdf** [comment]
> @gongdf see https://www.yuque.com/easy-team/egg-vue/web 和 https://www.yuque.com/easy-team/egg-react/web

好的
