### ISSUE TITLE
html-webpack-plugin配置问题

### ISSUE THREAD

**Issue by gongdf** [easy-team/easywebpack#50]
我需要改变html输出的目录
entry: 'app/web/**/*.js',
output: {
        path: path.resolve(__dirname, 'app/public'),
        publicPath: 'public',
 },
plugins: {
        html: {
            minify: false,
            filename: path.resolve('./app/view/[name].html')
        },
 },
配置后输出的文件名变成了0，1，2这种，我怎么用entry的js文件名作为html文件名（不更改l输出目录默认是用的entry的js文件名），就是[name]那个地方怎么取

**Comment by hubcarl** [comment]
默认就是用 entry 作为 html 的文件名，如果要改变 html 目录，可以配置  buildDir

**Comment by gongdf** [comment]
> @gongdf 默认就是用 entry 作为 html 的文件名，如果要改变 html 目录，可以配置 buildDir

可以了，谢谢
