### ISSUE TITLE
egg项目热更新问题求助

### ISSUE THREAD

**Issue by gongdf** [easy-team/easywebpack#51]
项目情况：
  用easywebpack将web目录（模板、前端资源的源文件）的源文件编译生成egg需要的view、public。
![image](https://user-images.githubusercontent.com/18187732/53136356-a54cb380-35b9-11e9-8a5c-e7efafd1733b.png)

问题： egg本地启动(npm run dev)时用egg-webpack通知了easywebpack编译成功，但easywebpack是内存编译，不落地磁盘，导致egg渲染找不到模板文件、静态资源文件

**Comment by hubcarl** [comment]
@gongdf  如果是自定义实现，看 egg-webpack  readme 使用说明。 easywebpack + egg 体系这些都解决了， 具体看 对应工程方案  https://www.yuque.com/easy-team

**Comment by gongdf** [comment]
> @gongdf 如果是自定义实现，看 egg-webpack readme 使用说明。 easywebpack + egg 体系这些都解决了， 具体看 对应工程方案 https://www.yuque.com/easy-team
> 
> * https://www.yuque.com/easy-team/egg-vue/build
> * https://www.yuque.com/easy-team/egg-react/build

大部分问题都解决了，谢谢。
现在html不能更新，我想在html-webpack-pluging完成后搞个页面刷新来实现，有对应的钩子可以用吗？（我看文档说Egg 服务端渲染项目时，devServer 配置是无需的，即使配置了也无效。），这个应该也是要在dev-server中运行的
