### ISSUE TITLE
html-webpack-pluging的配置求助

### ISSUE THREAD

**Issue by gongdf** [easy-team/easywebpack#52]
html: {
            minify: false,
            template: path.resolve(__dirname, 'app/web/page/[entryName]/[entryName].js')
 },

多页面怎么自定义template，就是entryName那个地方怎么才能拿到入口文件的名称（在配置文件中）

**Comment by hubcarl** [comment]
https://www.yuque.com/easy-team/frontend/oy1dub @gongdf 

![image](https://user-images.githubusercontent.com/4983042/54417124-3a1b7a80-473c-11e9-8c56-b7273cda2871.png)
