### ISSUE TITLE
多页面项目中有些页面的生成我希望当模板来使用不需要inject js/css,html-webpack-pluging怎么配置？

### ISSUE THREAD

**Issue by gongdf** [easy-team/easywebpack#54]
plugins: [
        {
            html: false
        },
        {
            env: 'prod',
            name: new CleanWebpackPlugin('app/view')
        },
        new HtmlWebpackPlugin({template, filename, minify, hash, inject, chunks}),
        new HtmlWebpackPlugin({template, filename, minify, hash, inject, chunks}),
        new HtmlWebpackPlugin({template, filename, minify, hash, inject, chunks})
    ]
类似这样我把easywebpack的增强配置html禁用掉，配上原生的HtmlWebpackPlugin，就只会生成最后一条配置的html,前面两个就没生成出html文件

**Comment by hubcarl** [comment]
![image](https://user-images.githubusercontent.com/4983042/54898429-44413400-4f07-11e9-8eba-22f7bbf9d363.png)
@gongdf 用 customize 试试，直接 webpackConfig.plugins.push(new HtmlWebpackPlugin({template, filename, minify, hash, inject, chunks}))

**Comment by hubcarl** [comment]
希望当模板来使用不需要inject js/css,html-webpack-pluging怎么配置

> 建议可以放到单独目录

**Comment by gongdf** [comment]
> 希望当模板来使用不需要inject js/css,html-webpack-pluging怎么配置
> 
> > 建议可以放到单独目录, 不经过 entry 处理

我这边模板里面的img src要处理
