### ISSUE TITLE
有配置可以在dev 热更新下编译完也让文件落地磁盘吗？

### ISSUE THREAD

**Issue by gongdf** [easy-team/easywebpack#55]
我的项目根据需要必须用多个html片段组成页面，片段的引用都是按路径读取磁盘的文件，导致在dev环境下开发没得搞（找不到文件）

**Comment by hubcarl** [comment]
@gongdf 这个不行， 建议你改变实现方式。 html片段组成页面建议你用  nunjucks 方式，可以include  html 模板

**Comment by gongdf** [comment]
> @gongdf 这个不行， 建议你改变实现方式。 html片段组成页面建议你用 nunjucks 方式，可以include html 模板 https://github.com/easy-team/easywebpack-multiple-html-boilerplate

好的，谢谢
