### ISSUE TITLE
多项目开发时, 端口占用问题

### ISSUE THREAD

**Issue by gongdf** [easy-team/easywebpack#58]
![image](https://user-images.githubusercontent.com/18187732/62607972-907a9700-b931-11e9-96b5-f524b54bc647.png)
我先开一个项目按默认端口配置，再开一个项目按上图配置后页面请求资源（js等）时请求失败，node项目控制台报错：ERROR 8480 [xxxx] nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:9000。

**Comment by hubcarl** [comment]
@gongdf 是 Egg 项目还是纯前端项目？

**Comment by gongdf** [comment]
Egg 项目

**Comment by gongdf** [comment]
上面描述有问题，应该是只要配了port:9100，就会报那个错误，跟其他项目开不开没关系

**Comment by gongdf** [comment]
@hubcarl 大佬有时间看了没

**Comment by hubcarl** [comment]
@gongdf 这个测试了一下，是可以运行的，端口会自动增加的。 是什么系统？ package.json 依赖贴一下看看

**Comment by hubcarl** [comment]
@gongdf 我先看看

**Comment by hubcarl** [comment]
@gongdf  proxy.host 手动指定一下
```
config.webpack = {
      port: 9100,
      proxy: {
        "host": "http://127.0.0.1:9100",
      },
 },
```

**Comment by hubcarl** [comment]
@gongdf  问题找到了，指定端口时，proxy 的端口没有更新到， 重新安装一下 egg-webpack@4.5.1 依赖

**Comment by gongdf** [comment]
@hubcarl 可以了，O(∩_∩)O谢谢
