### ISSUE TITLE
不能在output上面添加额外的属性比如crossOriginLoading

### ISSUE THREAD

**Issue by zhugexiansheng** [easy-team/easywebpack#59]
需要监听到上传了cdn的打包之后的js的错误信息，因为output不能添加crossOriginLoading，导致异步加载的js没有crossorigin的属性

**Comment by zhugexiansheng** [comment]
希望output能加上支持其他原生属性的配置

**Comment by zhugexiansheng** [comment]
![image](https://user-images.githubusercontent.com/13861291/63821298-0c8b5c00-c97f-11e9-90ef-293ece227042.png)
希望大佬在这里加上能支持其他原生配置的东东

**Comment by hubcarl** [comment]
@zhugexiansheng  没明白你具体要做啥？请具体说明是哪个配置或插件或loader？不支持的可以自己直接配置原生配置

**Comment by zhugexiansheng** [comment]
> @zhugexiansheng 没明白你具体要做啥？请具体说明是哪个配置或插件或loader？不支持的可以自己直接配置原生配置

想要在webpack的output配置上增加一个crossOriginloading的配置
![image](https://user-images.githubusercontent.com/13861291/63928646-80faf380-ca82-11e9-8ed5-6f6e22432339.png)
但是在使用了easywebpack之后，发现直接这样
![image](https://user-images.githubusercontent.com/13861291/63928843-e818a800-ca82-11e9-8fe7-cbd3275c2641.png)
配置，没有生效

**Comment by hubcarl** [comment]
@zhugexiansheng 可以先通过如下方式去修改生成的 webpackConfig， 你这种情况我看一下

![image](https://user-images.githubusercontent.com/4983042/63987140-9a934e00-cb09-11e9-84d1-803d1de65d54.png)

**Comment by zhugexiansheng** [comment]
测试了是有的，之前因为是域名一致所以webpack没有加上crossorigin这个属性，变成cdn域名之后就可以了
