### ISSUE TITLE
egg + vue + ts 的项目，只要npm run debug 就会卡在一个webpack努力编译中的页面，求解！！！！

### ISSUE THREAD

**Issue by ycvcb123** [easy-team/easywebpack#67]
![image](https://user-images.githubusercontent.com/15381888/70150464-02e36400-16e5-11ea-86b7-e85ff8101b8e.png)

**Comment by ycvcb123** [comment]
@hubcarl 大神方便解答下吗？

**Comment by hubcarl** [comment]
@ycvcb123 你什么系统? 我明天试试

**Comment by hubcarl** [comment]
@ycvcb123 你什么系统? 我明天试试

**Comment by ycvcb123** [comment]
@hubcarl easywebpack-cli 选下面的配置，新建的项目，npm run debug就会出现上面在编译中的情况

![image](https://user-images.githubusercontent.com/15381888/70591607-abc41e80-1c11-11ea-9237-8a7180f2ba11.png)

**Comment by hubcarl** [comment]
@ycvcb123 是vscode直接调试还是chrome方式调试，chrome方式试了下，没有问题，vscode得再试试

**Comment by funkyLover** [comment]
@hubcarl 我这边也有一样的问题

不知道你说的chrome的调试方式没问题是指用chrome就能正常调试吗？

但是用`debug`模式运行时，请求页面卡在了这个页面上

![屏幕快照 2020-01-14 17 16 32](https://user-images.githubusercontent.com/5418228/72343288-737c9800-3709-11ea-9878-62cc1c60fe83.png)

请求感觉还没有到egg的进程，怎么调试？

**Comment by ycvcb123** [comment]
@hubcarl vscode直接调试就会卡住

**Comment by funkyLover** [comment]
感觉像是前端资源的构建卡住了

**Comment by hubcarl** [comment]
chrome 可以调试 devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9999/__ws_proxy__

**Comment by hubcarl** [comment]
@ycvcb123 断点打在哪里？ controller 里面？

**Comment by hubcarl** [comment]
https://github.com/easy-team/egg-vue-typescript-boilerplate/issues/14

**Comment by funkyLover** [comment]
> chrome 可以调试 devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9999/**ws_proxy**

@hubcarl 详细情况是这样的

1. npm run debug, 没有报错能运行
1. 打开 `chrome://inspect` 也能看到对应的debugger进程（见下图1）

问题是

1. 进到chrome的devtools，在source下并看不到任何业务代码文件，使用 `command + p` 也搜索不到任何业务代码文件，只能看到node_modules的文件（见下图2）
1. 前端页面卡住了，卡在那个 `webpack 正在努力编译中...` 的页面，我想调试 egg 服务，那前端的请求都写好了，我就是想打开前端页面由前端发送请求出去，但现在 `npm run debug` 时，前端页面根本打不开（下见图3），难道只能启动debug然后用postman一类的工具构造请求吗。

图1

![屏幕快照 2020-01-16 10 12 19](https://user-images.githubusercontent.com/5418228/72487680-c2314b80-3849-11ea-960c-9341225257f6.png)

图2

![屏幕快照 2020-01-16 10 11 16](https://user-images.githubusercontent.com/5418228/72487760-ff95d900-3849-11ea-8936-fae8dcbd34eb.png)

图3

![72343288-737c9800-3709-11ea-9878-62cc1c60fe83](https://user-images.githubusercontent.com/5418228/72487776-0d4b5e80-384a-11ea-962d-fd14faf687fa.png)
