### ISSUE TITLE
url-loader  options 存在bug 

### ISSUE THREAD

**Issue by webaifei** [easy-team/easywebpack#68]
### 问题：
webpack.config.js配置如下
```
loaders: [
{
        urlimage: {
          options: {
            limit: 2000,
            name: 'img/[contenthash].[ext]'
          }
        }
      }
]
```
使用 easy print  打印最终配置， name 配置项没有生效
```
[ { loader: 'url-loader',
    options: { limit: 2000, name: 'img/[name].[ext]' } } ]

```

###  期望
name 配置生效

**Comment by HiuYanChong** [comment]
搜了一下代码，这个好像自定义不了

内置 [url-loader 的 name 选项](https://github.com/easy-team/easywebpack/blob/ce924aabe051c82349f4a95d4955e2dc9853ea8c/config/loader.js#L100) 读取 `this.webpackInfo.imageName`

`this.webpackInfo.imageName` 赋值逻辑在[这里](https://github.com/easy-team/easywebpack/blob/d36813ef5418c62251ba764dac2cdfa4907569f1/lib/core/output.js#L16)

所以如果需要带 hash，在 `webpack.config.js` 里面设置 ` imageHash: true ` 就可以了

**Comment by hubcarl** [comment]
@webaifei 临时办法，可以禁用urlimg，然后自己配一个或者customize里面处理一下

**Comment by hubcarl** [comment]
@HiuYanChong 看看是否可以覆盖配置，如果可以，可以提个pr

**Comment by HiuYanChong** [comment]
@hubcarl OK, 我瞧瞧，一并梳理下哪些内置 loader 存在这个问题吧

**Comment by webaifei** [comment]
@hubcarl 
👌  已经使用如下代码解决问题
```
customize(webpackConfig){ // 此外 webpackConfig 为原生生成的 webpack config
    webpackConfig.module.rules[4].use[0].options.name = 'img/[contenthash].[ext]';
    return webpackConfig;
  }
```
