### ISSUE TITLE
请教一下，easy zip 的执行流程在哪看？

### ISSUE THREAD

**Issue by ycvcb123** [easy-team/easywebpack#69]
我现在希望把 app，config，public，package.json 放到一个文件夹中，但是不希望zip，我本地写脚本也是可以实现的，但是就是想请教下，easy zip的流程在哪里看？

**Comment by hubcarl** [comment]
@ycvcb123  如果是代码, easywebpack-cli 里面, https://www.yuque.com/easy-team/egg-vue/online 或者  https://www.yuque.com/easy-team/egg-react/online

**Comment by ycvcb123** [comment]
@hubcarl 嗨，我看在npm run start 的具体执行流程，想问下你们开发的时候是如何打断点调试的呢？

```js
node --inspect-brk (应该如何写后面的参数，我才能进入到断点中？)
```

![image](https://user-images.githubusercontent.com/15381888/71780643-22c9b880-3000-11ea-9d4b-8fd88b7430b9.png)

**Comment by hubcarl** [comment]
@ycvcb123 你这什么类型项目？ 启动方式依赖这个？

**Comment by hubcarl** [comment]
https://www.yuque.com/easy-team/easywebpack/build
