### ISSUE TITLE
静态js文件修改没有热更新

### ISSUE THREAD

**Issue by Niefee** [easy-team/easywebpack#70]
在`/src/static/lib.js`中修改文件，提示`Ignored an update to unaccepted module...`，代码没有更新到，`console.log`没有打印出内容。

**Comment by HiuYanChong** [comment]
`unaccepted module`, 看这提示是分析到这个文件没有被项目引用到，更新直接忽略。
项目是怎么使用引入这个文件的？

**Comment by Niefee** [comment]
在`/src/actions/getData.js`中`import { fn } from '../static/lib.js'，在`index.js`中 `import {get} from '../actions/getData.js'`。

**Comment by hubcarl** [comment]
@Niefee webpack entry 的js 代码加上如下代码：

```
if (module.hot) {
  module.hot.accept();
}
```
