### ISSUE TITLE
easywebpack  cssModule 源码没找到在哪

### ISSUE THREAD

**Issue by he4398** [easy-team/easywebpack#72]
easywepack4
easywebpack4 默认提供 /\.module\.(css|less|scss|stylus)/ 的文件规范的 CSS Module 特性，把 css module 的样式文件改成 /\.module\.(css|less|scss|stylus)/ 规范，这样就无需额外配置，从而同时支持 CSS Module 和 普通样式文件。

这个不生效呀

**Comment by hubcarl** [comment]
@he4398  目前是支持使用了 easywebpack-react 项目生效

**Comment by he4398** [comment]
非常感谢。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sky <notifications@github.com&gt;
发送时间: 2020年3月14日 18:07
收件人: easy-team/easywebpack <easywebpack@noreply.github.com&gt;
抄送: HeAn <1134106057@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[easy-team/easywebpack] easywebpack  cssModule 源码没找到在哪 (#72)





 
@he4398  目前是支持使用了 easywebpack-react 项目生效
