### ISSUE TITLE
webpack的alias配置咨询

### ISSUE THREAD

**Issue by roguexiaohuihui** [easy-team/easywebpack#74]
想新增一个alias，像vue脚手架默认填写的：
    resolve: {
        alias: {
            'vue$': 'vue/dist/vue.esm.js',
            '@': resolve('src')
        }
    },

即将@指向到某一个目录，比如app/web/目录，我在webpack.config.js文件添加了

module.exports = {
  egg: true,
  devtool: 'eval',
  target: 'web',
  entry: {
    admin: 'app/web/page/admin/index.js'
  },
  cssExtract: true,
  dll: ['vue', 'vue-router', 'vuex', 'axios', 'vuex-router-sync', 'vue-i18n'],
  plugins: {
    imagemini: false
  },
  alias: {
    '@': 'app/web'
  }
};

即配置项：

  alias: {
    '@': 'app/web'
  }

然后在app\web\framework\app.js里面通过这样引入模块，

import { bus } from '@/common/bus'

始终提示Can't resolve '@/common/bus'

**Comment by hubcarl** [comment]
@roguexiaohuihui 
- easy print -n resolve.alias 看看是否生效，如果生效了，看看path是否对，app/web 用绝对路径看看
- 直接通过 resolve.alias 配置看看
