### ISSUE TITLE
网卡名问题，，en0, en1

### ISSUE THREAD

**Issue by MrTurnRight** [easy-team/easywebpack#76]

**Comment by MrTurnRight** [comment]
utils.getIP()

**Comment by hubcarl** [comment]
@MrTurnRight  可以的，你这边提个 PR 把 ，我这边出现不了这种场景，主要获取节点的方式不确定，需要你这边根据时间情况获取

**Comment by MrTurnRight** [comment]
if (interfaces.eth0) {
for (let i = 0; i < interfaces.eth0.length; i++) {
if (interfaces.eth0[i].family === 'IPv4') {
ips.push(interfaces.eth0[i].address);
}
if (interfaces.eth1) {
for (let i = 0; i < interfaces.eth1.length; i++) {
if (interfaces.eth1[i].family === 'IPv4') {
ips.push(interfaces.eth1[i].address);
}

**Comment by hubcarl** [comment]
已发布新版本，重新安装依赖即可。
